SELECT 
    e.element_name,
    JSON_ARRAYAGG(
        JSON_OBJECT(
            'input_value'      VALUE iv.input_value_name,
            'input_value_type' VALUE iv.input_value_type
        )
        RETURNING CLOB
    ) AS input_types
FROM 
    app_elements e
LEFT JOIN 
    app_input_values iv ON e.element_name = iv.element_name
GROUP BY 
    e.element_name;



-- When ORDS (Oracle REST Data Services) returns a JSON array as a "justified string" (meaning it is being escaped and treated as a plain text string like "[{\"input_value\":\"A\"}]" 
-- instead of a true JSON structure), it usually happens because the SQL query result is being implicitly converted to a string by the database or ORDS, or the content type isn't set to application/json.
-- To fix this, you can use JSON_OBJECTAGG or JSON_QUERY with explicit formatting in your ORDS source query to ensure Oracle returns it as native JSON data.
    
SELECT 
    e.element_name,
    JSON_QUERY(
        ('[' || LISTAGG('"' || iv.input_value_name || '"', ',') WITHIN GROUP (ORDER BY iv.input_value_name) || ']'),
        '$' 
        RETURNING CLOB
    ) AS input_types
FROM 
    app_elements e
LEFT JOIN 
    app_input_values iv ON e.element_name = iv.element_name
GROUP BY 
    e.element_name;



/* Package to handle Input payload DB */

/*
// Example VBCS payload structure to send to ORDS
{
  "employeeId": "10024",
  "elementId": "HOUSING_ALLOWANCE",
  "effectiveStartDate": "2026-04-01",
  "inputValues": [
    { "name": "Amount", "value": "1500" },
    { "name": "Frequency", "value": "Monthly" },
    { "name": "Comments", "value": "Updated per request" }
  ]
}
*/


/*
function upsertInputValueImmutable(inputValues, name, value) {
  const index = inputValues.findIndex(item => item.name === name);

  if (index !== -1) {
    // Return a new array with the updated item
    return inputValues.map((item, i) => 
      i === index ? { ...item, value } : item
    );
  } else {
    // Return a new array with the new item appended
    return [...inputValues, { name, value }];
  }
}
*/

-- Header Table
CREATE TABLE element_entry_headers (
    entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR2(50),
    element_id VARCHAR2(100),
    effective_start_date DATE,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Child Table for Dynamic Input Values
CREATE TABLE element_entry_values (
    value_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id NUMBER REFERENCES element_entry_headers(entry_id) ON DELETE CASCADE,
    input_name VARCHAR2(100),
    input_value VARCHAR2(4000)
);

-- ORDS Handlers

BEGIN
    pkg_element_entries.create_entry(
        p_payload => :body,
        p_entry_id => :id
    );
    -- Return the generated ID back to VBCS
    -- :status_code := 201;
END;

BEGIN
    pkg_element_entries.update_entry(
        p_entry_id => :id,
        p_payload => :body
    );
END;


CREATE OR REPLACE PACKAGE pkg_element_entries AS
    -- Procedure to Insert a New Element Entry
    PROCEDURE create_entry (
        p_payload IN CLOB,
        p_entry_id OUT NUMBER
    );

    -- Procedure to Update an Existing Element Entry
    PROCEDURE update_entry (
        p_entry_id IN NUMBER,
        p_payload IN CLOB
    );
END pkg_element_entries;
/

CREATE OR REPLACE PACKAGE BODY pkg_element_entries AS

    PROCEDURE create_entry (
        p_payload IN CLOB,
        p_entry_id OUT NUMBER
    ) IS
        l_employee_id       VARCHAR2(50);
        l_element_id        VARCHAR2(100);
        l_start_date        DATE;
    -- Parse Header Fields
    BEGIN
        SELECT 
            JSON_VALUE(p_payload, '$.employeeId'),
            JSON_VALUE(p_payload, '$.elementId'),
            TO_DATE(JSON_VALUE(p_payload, '$.effectiveStartDate'), 'YYYY-MM-DD')
        INTO 
            l_employee_id, l_element_id, l_start_date
        FROM DUAL;

        -- Insert into Header Table
        INSERT INTO element_entry_headers (employee_id, element_id, effective_start_date)
        VALUES (l_employee_id, l_element_id, l_start_date)
        RETURNING entry_id INTO p_entry_id;

        -- Insert Dynamic Input Values using JSON_TABLE
        INSERT INTO element_entry_values (entry_id, input_name, input_value)
        SELECT 
            p_entry_id,
            jt.input_name,
            jt.input_value
        FROM JSON_TABLE(p_payload, '$.inputValues[*]'
            COLUMNS (
                input_name  VARCHAR2(100) PATH '$.name',
                input_value VARCHAR2(4000) PATH '$.value'
            )
        ) jt;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END create_entry;

    PROCEDURE update_entry (
        p_entry_id IN NUMBER,
        p_payload IN CLOB
    ) IS
        l_start_date DATE;
    BEGIN
        -- Update Header details if needed
        SELECT TO_DATE(JSON_VALUE(p_payload, '$.effectiveStartDate'), 'YYYY-MM-DD')
        INTO l_start_date
        FROM DUAL;

        UPDATE element_entry_headers
        SET effective_start_date = NVL(l_start_date, effective_start_date)
        WHERE entry_id = p_entry_id;

        -- Refresh Dynamic Input Values: Delete old entries and insert updated ones
        DELETE FROM element_entry_values WHERE entry_id = p_entry_id;

        INSERT INTO element_entry_values (entry_id, input_name, input_value)
        SELECT 
            p_entry_id,
            jt.input_name,
            jt.input_value
        FROM JSON_TABLE(p_payload, '$.inputValues[*]'
            COLUMNS (
                input_name  VARCHAR2(100) PATH '$.name',
                input_value VARCHAR2(4000) PATH '$.value'
            )
        ) jt;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END update_entry;

END pkg_element_entries;
/